pulsar_url="pulsar://localhost:6650"
pulsar_admin_url="http://localhost:8080/admin/v2"
function_api = "http://localhost:8080/admin/v3/functions"
presto_host = "localhost"
presto_port = 8081
tenant = "public"
namespace = "default"
logger_topic = "logger"
window = 60
