FROM apachepulsar/pulsar:2.6.1
WORKDIR /pulsar/connectors
RUN curl -o "pulsar-io-data-generator-2.6.1.nar" "https://archive.apache.org/dist/pulsar/pulsar-2.6.1/connectors/pulsar-io-data-generator-2.6.1.nar"
WORKDIR /pulsar
